default_auth:
  auth_pubkey_file:
    username: ayourtch
    # username: lucy-ci
    pubkey: /home/ubuntu/.ssh/id_rsa.pub
    privatekey: /home/ubuntu/.ssh/id_rsa
    passphrase: cisco123
# auth_password:
#   username: foo
#   password: bar

default_vote:
        success: --code-review +1
        failure: --code-review -1
        clear: --code-review 0

default_query:
        # query: status:open project:vpp limit:4
        # filter: (status:new OR status:open) project:vpp limit:1
    filter: (status:new OR status:open) (project:testproj OR project:testvpp) limit:3
    options: --all-approvals --all-reviewers --comments --commit-message --dependencies --patch-sets --submit-records
    # options: "" # --all-approvals --all-reviewers --comments --commit-message --dependencies --patch-sets --submit-records
    # ? per_batch_command
    # ? per_change_command
# default_batch_command: scripts/format-output
default_sync_horizon_sec: 8640000

# where to resolve the relative command paths from
command_rootdir: /home/ubuntu/s5ci/scripts

triggers:
  patchset_upload:
      regex: ^Uploaded patch set (?P<patchset>\d+)$
      # action:
      #  event: check_build
      action:
        command: run-build {{patchset.ref}} '' # {{regex.patchset}}
  faulure_recheck_request:
      regex: 'XXXXXfailure' # a crude infinite retry
      action:
        command: run-build {{patchset.ref}} '' # {{regex.patchset}}
  recheck_request:
      regex: 'recheck'
      action:
        command: run-build {{patchset.ref}} '' # {{regex.patchset}}
              # event: check_build
  retest_request:
      regex: 'retest (?P<testname>\w+)'
      action:
        command: run-build {{patchset.ref}} {{regex.testname}}
  echo_comment:
      regex: \secho (?P<testval>.+)
      # optional suppress_regex will delete the about-to-be-started jobs of the same name
      suppress_regex: Build http
      action:
        command: run-echo {{regex.testval}}
  run_two:
      regex: runtwo (?P<testval>\w+)
      action:
        command: run-two {{patchset.ref}} {{regex.testval}}

  test_comment:
      regex: test (?P<testval>\d+)(:? (?P<secondval>\w+))?
      action:
        event: test_command

cron_triggers:
  every_minute:
      #            sec  min   hour   day of month   month   day of week   year
      cron:        "0    *     *          *           *          *          * "
      action:
         command: run-cron once-per-minute
  funky:
      cron:        "0   30   9,12,15     1,15       May-Aug  Mon,Wed,Fri  2018/2"
      action:
         command: run-cron some-funky



patchset_extract_regex: '(?s)^Patch Set (?P<patchset>\d+):'

jobs:
        rootdir: /var/www/html/jobs
        root_url: http://s5ci-dev.myvpp.net/jobs

install_rootdir: /home/ubuntu/s5ci

hostname: gerrit-client
db_url: /home/ubuntu/s5ci/db/s5ci.sqlite3
autorestart:
        on_config_change: true
        on_exe_change: true

server:
  address: 136.243.48.188
  port: 29418
  poll_type:
      direct_ssh: {} # use built-in ssh client
      #     auth:
      #shell:
      #    command: /usr/bin/ssh
      #    args: ['-p', '29418', 'ayourtch@testgerrit.myvpp.net']

  poll_wait_ms: 5000
  syncing_poll_wait_ms: 1000
  # sync_horizon_sec: 600
  sync_horizon_sec: 0

