default_auth:
  auth_pubkey_file:
    username: ayourtch
    # username: lucy-ci
    pubkey: /home/ubuntu/.ssh/id_rsa.pub
    privatekey: /home/ubuntu/.ssh/id_rsa
    passphrase: cisco123
# auth_password:
#   username: foo
#   password: bar

default_query:
        # query: status:open project:vpp limit:4
        # filter: (status:new OR status:open) project:vpp limit:1
    filter: (status:new OR status:open) (project:testproj OR project:testvpp) limit:3
    options: --all-approvals --all-reviewers --comments --commit-message --dependencies --patch-sets --submit-records
    # options: "" # --all-approvals --all-reviewers --comments --commit-message --dependencies --patch-sets --submit-records
    # ? per_batch_command
    # ? per_change_command
# default_batch_command: scripts/format-output
default_sync_horizon_sec: 8640000

triggers:
  patchset_upload:
      regex: ^Uploaded patch set (?P<patchset>\d+)$
      # action:
      #  event: check_build
      action:
        command: scripts/run-build {{patchset.ref}} '' # {{regex.patchset}}
  faulure_recheck_request:
      regex: 'failure' # a crude infinite retry
      action:
        command: scripts/run-build {{patchset.ref}} '' # {{regex.patchset}}
  recheck_request:
      regex: 'recheck'
      action:
        command: scripts/run-build {{patchset.ref}} '' # {{regex.patchset}}
              # event: check_build
  retest_request:
      regex: 'retest (?P<testname>\S+)'
      action:
        command: scripts/run-build {{patchset.ref}} {{regex.testname}}
  echo_comment:
      regex: echo (?P<testval>.+)
      action:
        command: scripts/run-echo {{regex.testval}}

  test_comment:
      regex: test (?P<testval>\d+)(:? (?P<secondval>.+))?
      action:
        event: test_command

patchset_extract_regex: '(?s)^Patch Set (?P<patchset>\d+): '

# the below two must be in sync
bid_regex: 'Lucy-CI-bid (?P<bid_id>\d+) (?P<hostname>\S+)'
bid_template: 'Starting build http://s5ci-dev.myvpp.net/jobs/{{job_id}} on {{config.hostname}}'

jobs:
        rootdir: /var/www/html/jobs
        root_url: http://s5ci-dev.myvpp.net/jobs

hostname: gerrit-client

server:
  address: 136.243.48.188
  port: 29418
  # auth:
  poll_wait_ms: 5000
  syncing_poll_wait_ms: 1000
  # sync_horizon_sec: 600
  sync_horizon_sec: 0

