#!/bin/sh
set -eux

export ROOT_DIR=../..

rm -rf tmp
# (cd ${ROOT_DIR}; make regen-db) || exit
(cd ${ROOT_DIR}; make) || exit
mkdir tmp
mkdir dist || true
cp -r ${ROOT_DIR}/html tmp/
cp ${ROOT_DIR}/go-s5ci/go-s5ci tmp/
# echo 'PRAGMA journal_mode=WAL;' | sqlite3 tmp/s5ci.sqlite3
cp -r ${ROOT_DIR}/scripts tmp/
cp -r ${ROOT_DIR}/templates tmp/
cp ${ROOT_DIR}/config.yaml tmp/
cp s5ci-start.in tmp/s5ci-start.sh

if [ ! -e dist/nomad_0.10.4_linux_amd64.zip ]; then
  # curl -o tmp/nomad_0.9.3_linux_amd64.zip https://releases.hashicorp.com/nomad/0.9.3/nomad_0.9.3_linux_amd64.zip
  curl -o dist/nomad_0.10.4_linux_amd64.zip http://s5ci-images.myvpp.net/nomad_0.10.4_linux_amd64.zip
fi
if [ ! -e tmp/nomad ]; then
  (cd tmp; unzip ../dist/nomad_0.10.4_linux_amd64.zip)
fi


# massage the temp tmp/s5ci-start.sh and tmp/config.yaml
sed -ibak -e 's#{{ACTUAL_STORAGE_USER}}#u207247-sub2#' \
	  -e 's#{{ACTUAL_STORAGE_HOST}}#u207247-sub2.your-storagebox.de#' \
	  -e 's#{{ACTUAL_GERRIT_HOST}}#gerrit.fd.io#' tmp/s5ci-start.sh

# massage the config.yaml so it makes sense for us
sed -ibak -e 's#/home/ubuntu/s5ci#/s5ci#g' \
          -e '/^server:$/,$d' \
          -e 's#/var/www/html/jobs#/local/jobs#' \
          -e 's#http://s5ci-dev.myvpp.net/jobs#http://s5ci.myvpp.net/jobs#' \
          tmp/config.yaml
cat <<__EOC__ >>tmp/config.yaml
server:
  address: 52.10.107.188 # 136.243.48.188
  port: 29418
  poll_type:
      shell:
          command: /usr/bin/ssh
          args: ['-i', '/secrets/s5ci-key', '-p', '29418', 'test4aiuortch@gerrit.fd.io']
  # poll every minute
  poll_wait_ms: 60000
  # every 10 seconds when we know there is more data
  syncing_poll_wait_ms: 10000
  # keep this at zero
  sync_horizon_sec: 0
__EOC__

docker build -t s5ci-test -f docker-s5ci.txt .

# publish the result
# . /secrets/s5ci-publish-image
REV=$(git rev-list HEAD~1.. | head -n 1 | cut -c 1-10)
docker tag s5ci-test ayourtch/s5ci-test:${REV}
docker push ayourtch/s5ci-test:${REV}

