#!/bin/sh
set -eux

export ROOT_DIR=../..

rm -rf tmp
(cd ${ROOT_DIR}; make regen-db) || exit
(cd ${ROOT_DIR}; make) || exit
mkdir tmp
mkdir dist || true
cp -r ${ROOT_DIR}/html tmp/
cp ${ROOT_DIR}/target/debug/s5ci tmp/
cp ${ROOT_DIR}/go-s5ci/go-s5ci tmp/
cp ${ROOT_DIR}/db/s5ci.sqlite3 tmp/
# echo 'PRAGMA journal_mode=WAL;' | sqlite3 tmp/s5ci.sqlite3
cp -r ${ROOT_DIR}/scripts tmp/
cp -r ${ROOT_DIR}/templates tmp/
cp ${ROOT_DIR}/config.yaml tmp/
cp s5ci-start.in tmp/s5ci-start.sh

if [ ! -e dist/nomad_0.9.3_linux_amd64.zip ]; then
  # curl -o tmp/nomad_0.9.3_linux_amd64.zip https://releases.hashicorp.com/nomad/0.9.3/nomad_0.9.3_linux_amd64.zip
  curl -o dist/nomad_0.9.3_linux_amd64.zip http://s5ci-images.myvpp.net/nomad_0.9.3_linux_amd64.zip
fi
if [ ! -e tmp/nomad ]; then
  (cd tmp; unzip ../dist/nomad_0.9.3_linux_amd64.zip)
fi


# massage the temp tmp/s5ci-start.sh and tmp/config.yaml
. /secrets/s5ci-tweak-configs

docker build -t s5ci-test -f docker-s5ci.txt .

# publish the result
. /secrets/s5ci-publish-image

