#!/bin/sh

rm -rf tmp
(cd ..; make regen-db) || exit
(cd ..; make) || exit
mkdir tmp
cp ../target/debug/s5ci tmp/
cp ../db/s5ci.sqlite3 tmp/
cp -r ../scripts tmp/
cp -r ../templates tmp/
cp ../config.yaml tmp/
sed -ibak 's#/home/ubuntu/s5ci#/s5ci#g' tmp/config.yaml
docker build -t s5ci-test -f docker-s5ci.txt .
