#!/bin/sh -eux

trap '' INT
trap '' PIPE
trap '' HUP
trap '' QUIT
trap '' ABRT

echo run-build $1
env
START_TIME=`date`
echo Starting the job ... $START_TIME

PROC_LIMIT=5
SLEEPTIME=300
while NUMPROC=$(docker ps | grep -v 'CONTAINER ID' | wc -l); [ ${NUMPROC} -gt ${PROC_LIMIT} ] ; do
   NOW=$(date)
   echo ${NOW}: $NUMPROC is more than max allowed $PROC_LIMIT, sleeping for $SLEEPTIME seconds
   sleep $SLEEPTIME
done

if docker run --mount source=CCACHE,target=/CCACHE --shm-size=1024M --name $S5CI_JOB_NAME aytest /start.sh $1 $2 ; then
	echo Docker Success
	${S5CI_EXE} review-success -m "Build ${S5CI_JOB_URL} has finished: success"
else
	DOCKER_RES=$?
	echo Docker run result: ${DOCKER_RES}
	${S5CI_EXE} review-failure -m "Build ${S5CI_JOB_URL} has finished: failure"
fi
# | ts
sleep 5
exit 123
