name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install rust
      run: make install-rust
    - name: build the rust version
      run: make build
    - name: build the golang version
      run: |
        (cd go-s5ci; go get || true)
        (cd go-s5ci; go build; ls -al)
