name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build the rust version
      run: make build
    - name: build the golang version
      run: |
        (cd go-s5ci; go get || true)
        (cd go-s5ci; go build; ls -al)
    - name: publish the build to docker
      env:
         DOCKER_CONFIG_JSON: ${{ secrets.DOCKER_CONFIG_JSON}}
      run: |
        mkdir ~/.docker
        echo ${DOCKER_CONFIG_JSON} >~/.docker/config.json
        (cd docker/build-s5ci; bash s5ci-build)
