name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build the golang version
      run: |
        (cd go-s5ci; go get || true)
        (cd go-s5ci; go build; ls -al)
    - name: build the rust version
      run: |
        sudo apt-get install -y make build-essential git libssl-dev pkg-config moreutils libpq-dev libsqlite3-dev
        source ~/.cargo/env && cargo install diesel_cli --no-default-features --features postgres,sqlite
        mkdir db
        source ~/.cargo/env && diesel setup --database-url db/s5ci.sqlite3
        make build
    - name: publish the build to docker
      env:
         DOCKER_CONFIG_JSON: ${{ secrets.DOCKER_CONFIG_JSON}}
      run: |
        mkdir ~/.docker
        echo ${DOCKER_CONFIG_JSON} >~/.docker/config.json
        (cd docker/build-s5ci; bash s5ci-build)
